name: CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
    - name: update linux
      run: sudo apt update 
    - name: update Rust
      run: make install
    - name: Check Rust versions
      run: make rust-version
    - name: build Rust
      run: make release
    - name: Format
      run: make format
    - name: Lint
      run: make lint
    - name: CRUD
      run: make crud
    - name: Test
      run: make test
    - name: upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-binary-artifact
        path: target/release/int6_individual2
    - name: pull repository
      run: git pull
    